# Generated by Django 2.2 on 2020-02-27 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reefr_api', '0005_auto_20200227_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
