# Generated by Django 2.2 on 2020-02-27 21:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reefr_api', '0009_auto_20200227_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('unit', models.CharField(max_length=32)),
                ('min_safe', models.FloatField()),
                ('max_safe', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='tank',
            name='volume',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=255)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reefr_api.ParameterType')),
                ('tank_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reefr_api.Tank')),
            ],
        ),
    ]
