# Generated by Django 2.2 on 2020-02-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reefr_api', '0011_userparametertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.FloatField()),
                ('measured_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=255)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reefr_api.ParameterType')),
                ('tank_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reefr_api.Tank')),
            ],
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
