# Generated by Django 2.2 on 2020-02-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reefr_api', '0012_auto_20200227_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametertype',
            name='unit',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
