# Generated by Django 2.2 on 2020-02-27 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reefr_api', '0013_auto_20200227_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametermeasurement',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
