# Generated by Django 2.2 on 2020-02-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reefr_api', '0014_parametermeasurement_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametermeasurement',
            old_name='measurement',
            new_name='value',
        ),
    ]
