# Generated by Django 2.2 on 2020-02-28 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reefr_api', '0017_equipment_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='')),
                ('tank_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reefr_api.Tank')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
