# Generated by Django 2.2 on 2020-02-28 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reefr_api', '0018_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametertype',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parametertype',
            name='user_profile',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
